services:
  - docker
language: java
jdk:
  - openjdk14
branches:
  only:
    - master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: test
      name: "Source Build"
      jdk: openjdk14
      install: skip
      script: ./gradlew clean build --info --stacktrace --refresh-dependencies
      after_success:
        - ./gradlew jacocoRootReport coveralls
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: ./gradlew travisReleaseSnapshot --info
    - stage: deploy
      name: "Deploy to DockerHub"
      if: type != pull_request
      install: skip
      script: bash docker_push.sh
notifications:
  email:
    on_failure: always
    recipients:
      - lichtenberger.johannes@gmail.com
after_failure:
  - cat ./logs/sirix.log